version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                uid: 1000
        ports:
            - "80:80"
        environment:
            - APACHE_RUN_GROUP=#1000
            - APP_NAME=ELibrary
            - APP_ENV=local
            - APP_KEY=base64:ng7qch0X4bCZ5BnOiTr6WlWpeXxvAP/wcwxPjsxupVI=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - ASSET_URL=http://localhost
            - LOG_CHANNEL=stack
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mysql
            - DB_HOST=galanlibrary.cdkw804eqno6.ap-southeast-1.rds.amazonaws.com
            - DB_PORT=3306
            - DB_DATABASE=galan_library
            - DB_USERNAME=admin
            - DB_PASSWORD=tarantula2504
            - BROADCAST_DRIVER=log
            - CACHE_DRIVER=file
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=sync
            - SESSION_DRIVER=file
            - SESSION_LIFETIME=120
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=7024220f7f7d2f
            - MAIL_PASSWORD=b6f28b126a7d93
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false
            - PUSHER_APP_ID=
            - PUSHER_APP_KEY=
            - PUSHER_APP_SECRET=
            - PUSHER_APP_CLUSTER=mt1
            - MIX_PUSHER_APP_KEY="1"
            - MIX_PUSHER_APP_CLUSTER="1"
        volumes:
            - laravel-elibrary-app:/var/www/html/public
            - laravel-elibrary-app:/var/log/apache2
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: 872M
    phpmyadmin:
        image: 'phpmyadmin:latest'
        environment:
            PMA_HOST: galanlibrary.cdkw804eqno6.ap-southeast-1.rds.amazonaws.com
            MYSQL_USER: admin
            MYSQL_PASSWORD: tarantula2504
        restart: unless-stopped
        ports:
            - "8080:80"
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 128M

networks:
    laravel-elibrary-network:
volumes:
    laravel-elibrary-app:
    laravel-elibrary-db: