version: '3.8'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
        - .:/var/www
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
        - APP_ENV=production
        - APP_DEBUG=false
        - APP_URL=https://galanlibrary.my.id
        - ASSET_URL=https://galanlibrary.my.id
        - DB_CONNECTION=mysql
        - DB_HOST=galanlibrary.cdkw804eqno6.ap-southeast-1.rds.amazonaws.com
        - DB_PORT=3306
        - DB_DATABASE=galan_library
        - DB_USERNAME=admin
        - DB_PASSWORD=tarantula2504

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - .:/var/www
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/snippets:/etc/nginx/snippets
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/html
        depends_on:
        - php-fpm
        - certbot

    certbot:
        image: certbot/certbot
        volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/html
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: galanlibrary.cdkw804eqno6.ap-southeast-1.rds.amazonaws.com
            MYSQL_USER: admin
            MYSQL_PASSWORD: tarantula2504
        restart: unless-stopped
        ports:
        - "8080:80"